name: auth_demo_flutter
description: A Flutter demo app with login/signup using GetX and Spring Boot backend.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  flutter_2fa: ^1.0.4
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
